research_problem_task:
  description: >
    Identify three independent research projects you need to execute to answer the high level
    research question {research-question} based in the domain of {domain}. These research projects should
    be much smaller in scope in comparison to the provided research question and should be completable in a 6 month timeframe by a PhD student. 
    Identify the goals of these research projects that will help answer the high-level research question 
  expected_output: >
    Three independent research project descriptions with a title, goal, a 4-6 sentence paragraph description of how to achieve this goal, and contributions to answering the high level
    research question {research-question}
  agent: researcher

create_search_queries_task:
  description: >
   Read the project description from the previous task. Then create 5 search queries with no more than two search terms/keywords relevant to the 
   project description. These search queries should be optimized for retrieving relevant related research in the field of {domain}.
   An example of a search query is: search term 1 search term 2. 
  expected_output: >
    A list of 5 search queries with key phrases and keywords to find literature related to the current project.
  agent: literature_reviewer